---
abstract: 'Provides a means of parsing and manipulating ISO-8601 intervals and durations.'
author:
  - 'Brian Phillips <bphillips@cpan.org>'
build_requires:
  File::Find: '0'
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-ISO8601-Interval
requires:
  Carp: '0'
  DateTime::Duration: '0'
  DateTime::Format::ISO8601: '0'
  Params::Validate: '0'
  overload: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/brianphillips/DateTimeX-ISO8601-Interval/issues
  homepage: http://search.cpan.org/dist/DateTimeX-ISO8601-Interval/
  repository: git://github.com/brianphillips/DateTimeX-ISO8601-Interval.git
version: '0.003'
x_authority: cpan:ROBN
